name: render ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Deploying to Render
        users: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true